pipeline {
    agent {
        docker 'docker-agent-alpine  '
    }
    
    environment {
        DOTNET_VERSION = '7.0'
    }

    stages {
        stage('Checkout') {
            steps {
                // שלב זה מוודא שאנו שולפים את הקוד מתוך Git
                git 'https://github.com/EliiShh/TryJenkins.git'
            }
        }
        stage('Build') {
            steps {
                // שלב זה בונה את הפרויקט
                script {
                    sh 'dotnet build TryJenkins/TryJenkins.csproj'
                }
            }
        }

        stage('Test') {
            steps {
                // שלב זה רץ את המבחנים אם ישנם
                script {
                    sh 'dotnet test TryJenkins/TryJenkins.csproj'
                }
            }
        }

        stage('Run Application') {
            steps {
                // שלב זה רץ את התוכנית ומדפיס את הפלט לקונסול
                script {
                    sh 'dotnet run --project TryJenkins/TryJenkins.csproj'
                }
            }
        }
    }

    post {
        success {
            echo 'Build succeeded!'
        }
        failure {
            echo 'Build failed!'
        }
    }
}
